server:
  port: 0

spring:
  application:
    name: max-product
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/max}
    username: ${DATABASE_USERNAME:max}
    password: ${DATABASE_PASSWORD:max}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    schemas: product
  jpa:
    properties:
      hibernate:
        default_schema: product
  redis:
    host: max-redis
    port: 6379

management:
  endpoints:
    web:
      base-path: /products/actuator
      exposure:
        include: ['*', 'prometheus']

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}